version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postmaker-postgres
    environment:
      POSTGRES_DB: postmaker
      POSTGRES_USER: postmakerAdmin
      POSTGRES_PASSWORD: postmakerPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postmakerAdmin -d postmaker" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: